### ISSUE TITLE
Back to BAIN 

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#219]
Opening this to group BAIN related TODOs:
- [x] related to skip stuff - packages with the master esm in them - anneal fails: http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/?p=25149806 (should be fixed in https://github.com/wrye-bash/wrye-bash/commit/fd2dbfda6e08551b7de4b9dbc0d6a10928b907cd)
- [x] skip stuff - see #270
  - [ ] why skipping any path that ends in `config` ?
  - [ ] maybe ignore thumbs.db etc also when calculating package structure ?
  - [x] do not directly use skipped dirs like u'--' and Bash - see: 514651b62965ab015b61d90e2ec79085e4cc27ad -> done: https://github.com/wrye-bash/wrye-bash/commit/a34b27aea5ab8a726bc5911ee1a26ff9db8a31df
- [x] refreshing installers should take into account Data: #277
- [x] different color settings for markers vs invalid: #276
- [ ] Ini tweaks should only be installed if on an ini tweaks folder _with no subfolders_
- [x] autobcfs: http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/?p=24260364 (edit: https://github.com/wrye-bash/wrye-bash/commit/e9e064de05982d1b3af59c59ae15ec17d9f0ce28)
- package quirks:
  - [x]  docs break complex bains -  ~~unconfirmed~~ http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/page-6#entry24315318 - edit - actually this is expected behavior and it stays - docs ! -> done: https://github.com/wrye-bash/wrye-bash/commit/309b083b986d1df7e53a85fbfb720cdb1610f140
  - [x] html docs left behind - ~~unconfirmed~~: http://forums.bethsoft.com/topic/1536340-wrye-bash-thread-105/#entry24322868 - edit - actually this is expected behavior not much to do about it - docs ! -> done: https://github.com/wrye-bash/wrye-bash/commit/309b083b986d1df7e53a85fbfb720cdb1610f140
- [x]  BSA conflict levels should be shown in hex as well -> http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/page-3#entry25238132 done: 1d8e35b74b94b47bc91878d57f1a9eaae482f4a7)
- [ ] BSA conflicts enhancements : http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-3#entry25314192
- [ ] refactor common code in Installer install

Refresh:
- [x] DLClist.txt and masterlist.txt -> 5608ddcc4490378ca9f29edecc412948bc169b46
- [x] ~~related to #277 - maybe add some minimal refresh of the data folder anyway  OnShow installers? Refresh espms ? Couple with mods refresh ?~~ nope, the problem should be addressed at the root - #265 
- [x] dest_src should be updated as part of the attributes_process !
- [x] projects are refreshed no matter what - for instance delete a project (or package  ?) - delete_Refresh will call irefresh('I...') which will refresh projects as `(isdir and not installer.refreshed)` will return true in refreshInstallers(). That's unneeded and costly !
- [x] consider exposing scanning of top level espms as an ini setting -> dropped altogether
- [ ] we define the mtime of a project as the max time of its subfiles - this results in calls to `os.walk` both in InstallerProject.refreshSource as well as in refreshInstallersNeeded. Shouldn't we check only the files that BAIN tracks - so the processing be done in refreshSizeCrcDate (where we already walk the installer but excluding skipped?). This will save an amount of time from refreshInstallersNeeded, which is needed. Plus if a file is skipped by BAIN why mark the installer as changed ? Plus we should check for _differences_ in mtime not just the max one (think of copying a file with a random small mtime) -> needs issue
- [x] cancel in loading data should cancel - or not ? -> can't see how - at least make it faster (partly done in https://github.com/wrye-bash/wrye-bash/commit/2897a8f44d1137d505760be579812226ea3f4ba3)

Issues:
- memory performance: #263 
- mods/inis `installer` attribute is not updated correctly when for instance - I install mod ZZZ.esp from an installer YYY high in the install order while ZZZ.esp is also installed by another installer XXX lower in the order when uninstalling YYY does not cede ownership of the mod back to XXX. May seem not a huge deal but actually points to the suboptimal way of detecting mod and ini changes - and this needs to be super optimal and correct so we only refresh mods and inis when needed (#205). --> edit #279

Backburner:
- [ ] omod extraction (if not binned) should be converted to use pack and unpack methods introduced in archives refactoring - it never checks for errors !
- [ ] `_extractOmods` vs `__extractOmods` ...

Lojack on skips: http://forums.bethsoft.com/topic/1536340-wrye-bash-thread-105/page-5#entry24408456

Leandor on skip voices: http://forums.bethsoft.com/topic/1570906-wrye-bash-thread-106/page-4#entry24801732

**Comment by Utumno** [comment]
@alt3rn1ty: One more point I need advice on (@lojack5 also):

```
    docExts = {u'.txt', u'.rtf', u'.htm', u'.html', u'.doc', u'.docx', u'.odt',
               u'.mht', u'.pdf', u'.css', u'.xls', u'.xlsx', u'.ods', u'.odp',
               u'.ppt', u'.pptx'}
...

    reReadMe = re.compile(
        ur'^.*?([^\\]*)(read[ _]?me|lisez[ _]?moi)([^\\]*)'
        ur'\.(txt|rtf|htm|html|doc|odt)$', re.I | re.U)
```

What this means is that not all doc extensions are allowed for readmes - should I amend that ?

```
    reReadMe = re.compile(
        ur'^.*?([^\\]*)(read[ _]?me|lisez[ _]?moi)([^\\]*)'
        ur'\.(' +ur'|'.join(docExts) + ur')$', re.I | re.U)
```

@leandor: the point you made about refresh here: http://forums.bethsoft.com/topic/1570906-wrye-bash-thread-106/?p=24792976 are in the code here: https://github.com/wrye-bash/wrye-bash/blob/77b504aca5d71e06606db95babab01d194ba44f8/Mopy/bash/bosh/__init__.py#L5646-L5660

So indeed some of the skipped folders are not refreshed from data (once BAIN is restarted!) but some others still are - lod textures in particular you mentioned. Compare to the skipping that takes place on archive/project level (in my branch - cleaner): https://github.com/wrye-bash/wrye-bash/blob/4142d009b9091a338282bef37724b9ee858f0a0f/Mopy/bash/bosh/__init__.py#L5246-L5279

I could add (some) of the rest in the skip refresh of Data/ - but now we hit an impasse for the reasons I describe in: http://forums.bethsoft.com/topic/1570906-wrye-bash-thread-106/page-4#entry24806046

Namely if we skip refreshing of skipped files from Data/ then (more or less on a restart) BAIN will loose track of those files being installed and won't display them as dirty nor uninstall them. @lojack5: I need your help here:

- do I understand this correctly ?
- how we go about fixing this ? I mean I can see that folders are skipped to save performance while scanning the data dir - but shouldn't we patch up somehow the uninstall (and dirty) ? Did you try to and decided that performance will suffer ? From my rewrite it would be easy and relativelly cheap to add (yet!) another attribute to installer (say Installer.skipped) that lists skipped files (and remaps them in the case of docs, images and strings) - but then on uninstall we should rescan Data/ to see if there (or add existence checks for all in Installer.skipped). This however won't update dirty.

So what you say ?

Re: beta - I want to have in my rewitte of the refreshDataSizeCrc - for performance and readability - but the issue I refer to above may need a deeper rewrite and I want BAIN to be fully functional for 307. This includes updating the docs to exactly match the code (for instance skipped dirs 'bash' and 'replacers' are not mentioned) - but let's start from the code. This is among others a _specification_ issue.

**Comment by alt3rn1ty** [comment]
Would allowing more doc types slow down operations ?
Or has the refactoring and optimisation you have done gained a lot more in speed that would make enabling more doc types negligible in terms of performance cost ?

If its a case of the former I would stick with the most popular needed, otherwise .. I do not know of any reason not to allow them, can the excluded file types be abused in any way ?

**Comment by leandor** [comment]
I understand your point about losing track of the files... but, keep in mind that at least specifically in the case of the DistantLOD files, LOD Meshes and LOD Textures files you'd never want to deal with those files at all, at least in a standard more up to date installation. 

Since they are totally auto generated by third party tools (TES4LODGEN for DistantLOD\* and TES4LL for LOD Meshes and Textures.)

That was the point of those skips, to prevent archives from installing files that you'd be overwriting with the tools. 

So, I don't see the lose tracking as a big issue myself, at least for those cases.

For any other cases, you're absolutely right... losing track would be an issue since any installed files would have been placed there by BAIN so, it would be nice that if you start to skip them, BAIN at least know that they need to be uninstalled.

I hope what I'm saying makes sense :)

**Comment by alt3rn1ty** [comment]
I cant remember if these are the same types of files but ..

See DynDOLOD for Skyrim http://www.nexusmods.com/skyrim/mods/59721/?
It uses TES5Edit and TES5LodGen

See the Output files in the Second post of a guide I did for making BAINs out of the whole setup and generated BTO files http://afkmods.iguanadons.net/index.php?/topic/4289-dyndolod-guide-for-wrye-bash-users/

While testing out what it generates ( and how far to go with its advanced settings before it started bringing my machine to its knees ), I had nine BAINs on the go at one point, all with different sets of generated LOD files.

In that case you really do need those files tracked 100%, CTDs are easily achieved with the wrong files / settings for lesser machines, and or continuing from the wrong save with the wrong files installed

**Comment by leandor** [comment]
Yeah, agreed then... I stand corrected, as Skyrim is a different world I mostly don't know about.

So, yes... I was being specific to Oblivion usage in my post, mostly because I didn't knew about those kind of tools/mod for Skyrim (man, I've been out of the loop with Skyrim modding for at least three years!)

And that mod looks kind of cool, if I weren't so burned out with Skyrim (still...) I'd looking forward to giving that a go :) Perhaps one day I'll start playing Skyrim again.

**Comment by Utumno** [comment]
Well in the distant lod at least I think they are not skipped because of a bug - can you spot it @leandor ?
It''s here: https://github.com/wrye-bash/wrye-bash/blob/77b504aca5d71e06606db95babab01d194ba44f8/Mopy/bash/bosh/__init__.py#L5646-L5660 ;)

I can go ahead and correct it but i want a solution for BAIN leaving files behind. Maybe forcing an anneal on toggling skip settings to on ? @lojack5 what you say ?

Re: docs - negligible performance - in the current beta implementation _no_ performance difference. So this is decided.

**Comment by Utumno** [comment]
And another question: we skip distant lod by skipping the dir (ahem) - would be faster to skip based on the extension `.lod` - @wrye-bash/bashers is this extension used in other stuff ? Would be safe to use that in skipping ? In distantlod folder there are also some `.cmp` files - what are those about ?

A rundown of lod meshes/textures would be useful to me - leandor's comments shed some light but a need a technical specification and I will squash it down to as fast as it can go ;)

So:
```
Skip DistantLOD
Skip LOD Meshes
Skip LOD Textures
Skip LOD Normals
```

**Comment by Utumno** [comment]
And another bug I need verified - from the OP:

> mods/inis installer attribute is not updated correctly when for instance - I install mod ZZZ.esp from an installer YYY high in the install order while ZZZ.esp is also installed by another installer XXX lower in the order when uninstalling YYY does not cede ownership of the mod back to XXX.

**Comment by alt3rn1ty** [comment]
Just popping in to let you know I will not be able to help for a while, moving house again in two days, all painting / wallpapering etc done at the new house already, tomorrow will be taking the old house to bits as much as possible and will not have internet until at the new house for a while after we move.
I would need to grab all the relevant DynDOLOD files again ( not currently using it on new machine ), but do intend to at a later date.

**Comment by leandor** [comment]
@Utumno: Ouch... I just saw it: 'distan**d**lod' >_<

((I'm the kind of person that makes those mistakes while typing :) But man, spotting that in the middle of all the other stuff was kind of hard on my brain at this time of the day :P))

**All of this that follows is specific to Oblivion!**

About DistantLOD: AFAIK, all those files are re-generated by TES4LODGEN... I fact, part of the process if to eliminate them before generating them again (TES4LODGEN does that automatically.) And you can even delete the DistantLOD folder and let it be regenerated. 

If ignoring by extension works better with the way the code is organized, I don't think there should be a problem with adding *.LOD and *.CMP to the exclusion list.  

As for what those CMP files do specifically, I don't really know... 

I know that .LOD files are what defines which far mesh (*_far.nif) is placed in the world. They're basically big tables containing objects (FORMIDs, which in turn points to a _far.nif through the corresponding record in the mod in which they are defined) and their position and rotation.  There are many LOD files for each worldspace: one file per cell. 

They're load order dependant, as the FORMID inside them is an absolute FORM (includes the Mod Index from the actual load order.) 
I have no idea what the *.CMP files do or what they are... they are obviously related to the worldspace as there is one per worldspace.

About LOD Meshes:
Those are simply *.NIF files that hold the model of a QUAD/Block of distant terrain. They're located at 'meshes\landscape\lod', and have names composed by the worldspace formid (in decimal) and the coordinate of their block, plus a decimal number at the end, which seems to be always 32 (probably the size of the block in cells)

LOD Meshes and Normals are normal DDS texture files that follow the same nomenclature of the NIFs above. The only difference is that the normals have appended '_fn.dds' to their name. 
They are located in folder 'textures\landscapelod\generated'.

This is the normal way the game handles its distant LOD... but Ethatron did something different with OBGE3 and OSCAPE, and that means, there could be possibly more type of files around when someone is using those. I never used it, so I don't really know how it works or how it differs from the standard LOD mechanism.

((AFAICT, the new OblivionReloaded still supports OSCAPE generated Far Terrain))

**Comment by Utumno** [comment]
Thanks @leandor - so this explains why distantlod was still scanned - still:

> I can go ahead and correct it but i want a solution for BAIN leaving files behind. 

Thanks for the info on distant lod also! Will come out quite handy. Note that in the same piece of code we could add skipping for 'meshes\landscape\lod' (check other games) and a few others.

**Comment by Utumno** [comment]
@leandor: I moved your post to the wiki - thanks :) Feel free to edit with info on BAIN's skip logic and @alt3rn1ty (hope all is going fine in the new house :)) with info for skyrim

In general we need good quality wiki posts - let me know if you want to add screenshots ;)

**Comment by Utumno** [comment]
@wrye-bash/bashers @lojack5:

Run across this: http://www.nexusmods.com/skyrim/mods/39492/?

Package Structure:
```
Mopy\
  INI Tweaks\
    Skyrim\
      Tutorials, Disabled [Skyrim].ini
      Tutorials, Enabled [Skyrim].ini
```

BAIN happily installs that but the ini tab does not see the tweaks - what goes on here ? Should(n't) we disallow this ?

**Comment by Sharlikran** [comment]
Quoting the Author:
> Download the archive and extract into your main Skyrim directory (not the data folder)

The author does tell people to install them by extracting the files into the Skyrim folder.  Which if people have a Mopy folder then this will work.  I checked it and Wrye does install the files into F:\Games\SteamApps\common\Skyrim\Data\INI Tweaks\Skyrim and as far as I know Wrye Bash/Smash?Flash doesn't look there.

I really don't see why we couldn't allow it but make this a feature request for a future version.  Wrye could look in the Mopy\INI Tweaks\[GmaeMode] folder and in the Data\INI Tweaks\[GameMode] folder for custom INI Tweaks.  The tweaks are only for Wrye Bash so it kind of makes sense to allow users some way to add them via the installers tab.

**Comment by Utumno** [comment]
Complexity - what I really want to know here is what package format we allow. As it is now as you saw it's broken - so the author, is wrong and BAIN dumps then to  a place that the ini tab does not see it.

@Arthmoor ?

**Comment by Sharlikran** [comment]
Respectfully speaking the author is not wrong and has stated that his mod or this file is to be manually installed into the Game folder.  A user that installs this using NMM or BAIN is not installing the file correctly.

My suggestion was to add a new feature for say 308 or 309 that has Wrye reading the Mopy folder and the Data folder for INI tweaks instead of only the Mopy folder as it does now.

**Comment by leandor** [comment]
Probably the author of that mod doesn't know that INI Tweaks can be placed inside the data folder and that Bash merges the two folders in a single view. I've installed countless of mods with INI Tweaks in them, and never had a problem adding them as an extra root folder to the archive (or in a package).

**Comment by Sharlikran** [comment]
@leandor that's odd, because I just tested this and it didn't work for Skyrim.  What INI Tweaks did you install and were they for Oblivion?  If the feature only works for Oblivion to me that's inconsistent and it should be available to all versions.

Maybe the feature was removed by accident somehow?  If previous versions allowed users to install INI Tweaks into the Data folder and merge them into a single view on the INI Tab then that feature should probably be added back or updated so it works with all game modes.

**Comment by leandor** [comment]
DarnNified UI mod comes with INI tweaks inside its archive. Also, I've made INI Tweaks myself for my installation of Oblivion Reloaded. 

And I've made ini tweaks for several other mods in the past, I don't remember which ones now. 

I think All Natural was one of them for recovering my color and weather setup after each install.

**Comment by Sharlikran** [comment]
Thanks for the feedback.  I don't have time to test 306 due to changes in work and some health concerns.  However, that information is very helpful because I can at least test Oblivion with those mods and see if the INI Tweaks show up like they have for you in previous versions.  If for some reason that no longer works as of 306 then previous versions will have to be tested to see when the feature was broken.

Again thanks for the feedback, I appreciate it.

**Comment by leandor** [comment]
No problem :) I'm using some of those mods in my current setup with the
bleeding edge branch, and for Oblivion they are working OK now.

I can test with Skyrim too if you want, as I'm using the same branch for
Skyrim as with Oblivion.

But Now I'm at work, so it'll have to wait until later when I get back home
:)

**Comment by Utumno** [comment]
What I suggest is that ini tweaks should be placed in an `Ini Tweaks` subfolder but _no subfolders in there (as Bash won't see those subfolders anyway - right ?)_ - no difference between skyrim and oblivion - you should not install ini tweaks in mopy, that's the tweaks that come with Bash - ini tab needs an overhaul yes

**Comment by Utumno** [comment]
What I suggest is that ini tweaks should be placed in an `Ini Tweaks` subfolder but _no subfolders in there (as Bash won't see those subfolders anyway - right ?)_ - no difference between skyrim and oblivion - you should not install ini tweaks in mopy, that's the tweaks that come with Bash - ini tab needs an overhaul yes, but that's up to @lojack5 (default tweaks should be out of user's reach, performance should be revisited, see #247)

But for BAIN:

```
Mopy\             # single top level folder allowed, whatever its name
  INI Tweaks\  # Bash dumps the contents of this in Data/Ini Tweaks
    Skyrim\       # now this should go, right ?
      Tutorials, Disabled [Skyrim].ini
      Tutorials, Enabled [Skyrim].ini
```

**Comment by Utumno** [comment]
And another issue: Bash skips top level directories in Data and in projects/packages that are named `replacers` - related to the ancient replacers tab - should I omit this ? - I say yes

**Comment by alt3rn1ty** [comment]
For Oblivion see the files Ini Tweaks extras and Ini Tweaks for DarN UI
http://www.nexusmods.com/oblivion/mods/35230/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Foblivion%2Fajax%2Fmodfiles%2F%3Fid%3D35230&pUp=1

For Skyrim see the file Skyrim INI Tweaks Xtra BAIN
https://dl.dropboxusercontent.com/u/86040572/Skyrim%20INI%20Tweaks%20XTra%20BAIN.7z

That is how alt3rn1ty do

And they all work fine, and as intended as far as I know - or should do anyway, I cant confirm on the Oblivion front these days, they certainly used to work okay, but heres the Skyrim ones in use ...

Screenshot 1 https://i.imgur.com/9siCfAL.jpg

Screenshot 2 https://i.imgur.com/ZsMIFVm.jpg

**Comment by alt3rn1ty** [comment]
Ref Replacers directory ..
I have never had a call to use such a named folder, nor seen one in use, maybe its a Morrowind thing from Wrye Mash days ?
I had a look for the old Wryemusings site to see if there was anything .. Sites down.
Needs someone with a long memory of those details

Maybe Melchor knows ? http://forums.bethsoft.com/topic/1106095-wrye-mash-stand-alone/

**Comment by Sharlikran** [comment]
Well it looks like I was wrong then.  I will have to test the latest version and that mod again.  I could swear that the INI tweaks didn't show up in Skyrim even though as leandor and alt3rn1ty have stated, they are to be installed using BAIN into the Data folder and Wrye should be recognizing them.

**Comment by Utumno** [comment]
Alright @alt3rn1ty (do accept your invitation here please !) - both those mods package their tweaks directly inside an Ini Tweaks directory - that's the correct way of doing it. The Mopy/Ini Tweaks is reserved for Bash default tweaks and should be not user edited. I will have to disallow installation of ini tweaks by BAIN to Data/ini Tweaks/any_subfolder. Meanwhile can someone go through the readme and edit this info in (no Mopy/ and Ini tweaks no subfolders) for valid BAIN structure - search for "ini tweaks". BAIN does not care if you name your top level folder Data/ or Mopy/ or Whatever/ - it will go and install in data full stop. So this mod's Ini tweaks end up in Data/Ini Tweaks/Skyrim - and Bash does not sees them.

Re: replacers - there was a "replacers" tab once - relic from those days ? Anyway will remove it from skipped dirs if no one turns up with a reason to be skipped.

**Comment by Sharlikran** [comment]
>  I will have to disallow installation of ini tweaks by BAIN to Data/ini Tweaks/any_subfolder

I was initially confused as to the functionality of installing INI Tweaks with BAIN.  Now that both @leandor and @alt3rn1ty have stated that installing INI Tweaks into the Data folder is common practice why would you disallow the installation of INI Tweaks?

**Comment by Utumno** [comment]
To `Data/ini Tweaks/any_subfolder` as opposed  to `Data/ini Tweaks/` :P

**Comment by Sharlikran** [comment]
Yeah you ninjad me while I was testing.  I was editing my post to ask if I understood it correctly while you were clarifying what you meant.  Thanks for the clarification, I appreciate it.

**Comment by Utumno** [comment]
Please someone go and edit the readme on that - Back to BAIN is amongst others a readme/specification issue. Now if only we had a nice testing package...

**Comment by Sharlikran** [comment]
Do you need one for the INI TWeaks?
[Disable Tutorials - INI Tweaks for Wrye Bash-39492-.zip](https://github.com/wrye-bash/wrye-bash/files/92203/Disable.Tutorials.-.INI.Tweaks.for.Wrye.Bash-39492-.zip)

I'm affraid I may not understand BAIN as much as I thought so @alt3rn1ty might be a better source if you need a more complex testing package.

**Comment by Utumno** [comment]
Sharl that's the mod I linked to initially :D (which seems to not have the skyrim subfolder though - apparently fixed ?)

**Comment by Sharlikran** [comment]
The original authors mod is not updated on the Nexus.  For testing, I made a new archive with the proper path to Data\INI Tweaks.

**Comment by Utumno** [comment]
Ok another question. I am rewriting the docs to describe what the code _does_ skip:

Skipped Files

BAIN skips the installation of some files and directories. The types of files skipped are:

- Silent skips. These are:
  - thumbs.db and desktop.ini files (actually any file path that ends in those strings)
  - _any path that ends in config_
  - the omod conversion directory (omod conversion data, fomod) - actually any top level package or subpackage file/directory that starts with those strings
  - the wizard images directory (or any file/directory that starts with `wizard images`)
  - Developer files. Any file or directory that begins with '--' and is at the top level of a package or a subpackage will be silently skipped. This is so that mod authors can include files related to a mod that are not required for it to work (eg. screenshots) in packages. 
- Non-standard directories. Standard directories include all the game's default directories (including those only found in BSAs by default) and 'ini', ini tweaks', 'pluggy', 'scripts', 'streamline' and '_tejon'. Installation of these directories may be forced by using the Has Extra Directories option. Files skipped because of this will be listed in the "Skipped" panel on the right. Even if Has Extra Directories option is checked directories that start with Bash (or the ones that are silently skipped) will still be skipped.
- Archives & executables. Executable files, apart from Script Extender plugins if the Skip OBSE Plugins option is disabled, and archives in packages will be skipped. Files skipped because of this will be listed in the "Skipped" panel on the right.
- Specified skips. There are a few options in BAIN to skip the installation of certain file types. If any such options are enabled, the file type(s) in question will be skipped.

Now can anyone explain to me why we are skipping files/directories that end in config ?
-------
I also see code that checks for the presence of 'masterlist.txt' or 'dlclist.txt' - why do we care about those ? @Arthmoor ? @lojack5 ?
Actually masterlist.txt or dlclist.txt are considered valid data files (like espms, bsas and inis). Why ? Is it related to wizards maybe ?

**Comment by Arthmoor** [comment]
I don't remember what masterlist.txt is for.

dlclist.txt is something that gets generated for Skyrim and lives in the same folder as plugins.txt. I have no idea why anyone would include that file in a BAIN installer but you never know. I'm pretty sure it only shows up if they're using mods from the Steam Workshop so it's probably blocked just in case it causes problems with that.

**Comment by Utumno** [comment]
Thanks @Arthmoor - it is not blocked actually - the strange thing is that it is used in a regular expression (https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/__init__.py#L4895-L4896) that is used to see if the subpackage contains valid files, and decide if it's a complex package or not:
https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/__init__.py#L5657-L5668

That's beyond me - and should probably be fixed

masterlist should be the boss masterlist (?)

What about Bash igoring file paths that end in _config_ ?

**Comment by Arthmoor** [comment]
Took another look. DLCList.txt does exist in Oblivion and it does get stored in the Data folder. It's definitely not something people should be including in a BAIN archive of any sort since the file specifically says not to alter it.

I don't think BOSS puts masterlist.txt into the Data folder, does it?

I have no idea why Bash is ignoring file paths with config in them.

**Comment by Sharlikran** [comment]
I can't see why anyone would want to put those files in a BAIN installer.  You wouldn't want to overwrite DLCList.txt if it were in the data folder so technically skipping that would be a good idea.  The masterlist on the other hand yeah, nobody should include that in a BAIN archive either.  Take it out if you want but I'd skip the DLCList.txt.  We can't control what authors do and regardless of our reasons they are going to do whatever they want.

With over 46700+ mods someone was bound to do something in order for a previous dev to skip those.

**Comment by Utumno** [comment]
They are not skipped - BAIN tests if they are there - @lojack5 please chime in :)

Could you guys test for me if BAIN does install those files ? Make a package with those and let me know

I am refactoring core BAIN @Arthmoor - no changes in behavior yet (apart from the first few items in the OP here and err, performance) but the time has come to get _back to BAIN_ so I will be needing testing of my changes and feedback. Please test: https://github.com/wrye-bash/wrye-bash/commits/utumno-200-refreshDataSizeCrc

**Comment by Sharlikran** [comment]
Sorry if I misunderstood but it's still odd.  I'd just decide what you feel is best as Lojack might be busy and may not answer.

However, if they check for them or skip them or whatever, I'd say masterlist.txt and DLClist.txt should not be installed if for some reason it is in a BAIN archive.  If it's checking for masterlist.txt or DLCList.txt then it shouldn't at this point because BOSS is no longer the sorting tool for this version.  Plus I don't see why masterlist.yaml would be needed either since some people don't use LOOT.  

Is it possibly because back in the day the routine may have had to update the load order?  Because Wrye now uses libloadorder.dll and because other refactoring, do you feel that's probably no longer needed?

If you can't think of why and if you feel it might be related to load order (because I can't think of much else) then just make sure after BAIN installs the mod that loadorder.txt is updated and whatever else already happens (per previous conversations) and bin checking for those files.

Since you are looking at BAIN at this point, although it may not be a priority, which is fine, please consider #269 if it's possible.

**Comment by Utumno** [comment]
Did anyoooonee teeest if those txts are installed ?
Re: #269 - skip mechanism has some serious bugs - see the OP. If those are fixed will surely have a look.

**Comment by Utumno** [comment]
@alt3rn1ty: I need a huge favor - @wrye-bash/bashers this goes to all of you. I need a final specification of valid vs invalid packages in the form of examples of accepted vs invalid package formats. This will best be set up as a wiki post.

I need this ASAP - that stands on my way of fixing BAIN for good - I can't really proceed on my second phase of refactoring till I have a concrete specification (with plenty of examples) on what BAIN should recognise. Now is the time to fix it, so please while I am at it, offer your knowledge. I need especially insight on docs placement (see #266) and egde cases like semi complex packages or stuff like:

```
00\
01\
  Data\ #allowed ?
  readme.txt #allowed ?
```

**Comment by Metallicow** [comment]
As far a an official spec... I believe this might be better done as a testbed of resources maybe with statistics, the existing code in the GUI and a dump of what BAIN actually *sees* as a valid package/project.

For example a python script(in a separate repo or something with some generic base files(.dds, .nif, .espm, etc...)) that zips up combinations, permutations with itertools based upon the now "classic" rules BAIN or users think would work based on a depth rule to generate test packages.
I would likely from that point then write a statistics like text dump def for BAIN, hook it in, direct bain to load the test archives/projects directory as my bashinstallers and then dump the data and flag examples that didn't or did work at runtime. Then maybe something such as sphinx could generate a nice html of everything for easy docing, debugging, readability with hyperlinks.

The biggest difference in most package structures is always whether the modder puts the "data" folder at the top of an archive or not, which doubles the number of choices available. and whatever other files may be floating around at a certain level.

Example archives structures for the spec could then be cherry picked from the testbed or be recreated like the wizbain demo with docs included maybe...

Most of the resources are already available in the bash code and or wizbain demo, so writing a testbed shouldn't be too hard. Just handle the testbed code like a brute force password cracker with a depth level of 3-4 and all the possible results should be generated easily.
...Just a thought...  
...might require a bit of HDSpace to generate the test archives and time to review the test cases tho...

**Comment by Utumno** [comment]
> This will best be set up as a wiki post.

@Metallicow: your post: https://www.dropbox.com/s/0s3xuqgakmbez04/20160204224448.zip?dl=0

**Comment by Metallicow** [comment]
@Utumno I understand what you are asking for..., but I do not have the personal time to do so. Sphinx can be modified to do any formatting you want for any language you want. It is a generator of text(which `can` compile to code), which is what you was asking for. A spec is specific. In my work we call it a 'proof' which comes before presstime. This is essentially a security issue that should validate files before making a spec as I see it. Wrye himself I believe understood fully exactly why Open Source code should be able to crack itself and explained so in a simple post long ago. Please take my offering of this open knowledge as a basic explanation of how to do it correctly(documented), or delete it and this post entirely. I was simply offeing a time based idea to offer a 100% solution.

-Metalio Bovinus

**Comment by saebel** [comment]
Various BAIN Issues:

- Refreshing/scanning an installer package should also refresh/scan the parallel folders/files in the data folder.

- After a data sync, BAIN does not remove the flag that there needs to be data synced, even though the files were correctly updated.

- Data sync suggestion: don't just list the number of files that are going to be updated/deleted, show the file names.  I accidentally agreed to a data sync that deleted files that it shouldn't have and would have caught had I seen the file names.  Thank goodness I had made a backup.

- General issue with files not being recognized as being changed when changed and vice versa.

- Wizard: Notes function does not appear to be working.  Syntax used is
Note "Text for the note"

- Wizard: Weird issues with displayed images.  When selecting an option, sometimes the image size would expand from the default 210 x 210 to 230 x 230, even though it was unnecessary for it to do so.  It stays at the zoomed ratio while toggling between selections, but returns to normal when continuing forward or back.  Blown up images look blurry and unprofessional.  My recommendation would be to have it set up so that an image never zooms larger than it's actual size.  That would solve the problem nicely, and graphic designers everywhere will thank you.

**Comment by Utumno** [comment]
@saebel: moved the wizard stuff to a new issue #272 - please post wizards stuff there 9and don't hold your breath)

Is this:

> - After a data sync, BAIN does not remove the flag that there needs to be data synced, even though the files were correctly updated.

still valid in latest code (https://github.com/wrye-bash/wrye-bash/archive/utumno-refresh-checks-data.zip) ?

**Comment by saebel** [comment]
"After a data sync, BAIN does not remove the flag that there needs to be
data synced, even though the files were correctly updated."

Hasn't been a problem yet.  Bot datasyncing and manually refreshing the
contents of a folder have been fine.

I did run into a weird issue when switching between Nehrim and Oblivion
using the same Oblivion Mods folder for both.  It's probably how I have
things set up, but if I make changes and selections with one game, those
changes are reflected in the other on the installer tab.  It then thinks
they are out of sync, and when the option to datasync is selected, it tried
to delete files from the installer that it shouldn't have only because
those sub-packages weren't selected for that game.  I ran into this before
and accidentally deleted files I shouldn't, bit this time around I caught
myself.

I don't think this is a big deal because I'm fairly certain my setup is
wrong.  The program is probably behaving exactly the way it should.  But I
wanted to mention it anyway just in case this behavior is not expected.

**Comment by Utumno** [comment]
> I don't think this is a big deal because I'm fairly certain my setup is wrong. The program is probably behaving exactly the way it should.

Or may not - Nehrim support is alpha I guess - the real answer to all these is profiles (see #250) but that is 308+

Opened an issue for your request : #273

**Comment by saebel** [comment]
I double checked everything, and it was a Bash.ini setting problem. I 
accidentally was pointing the Nehrim Bash Installer data to the Oblivion 
Mods Data folder.  I redid all of my link in the .ini files and 
everything seems to be working as expected.

One thing that is kind of odd is that the sorting and markers are 
different even though I'm using the same source mod folders.  That means 
every time I have to modify / organize one via Oblivion mopy I have to 
do it again using Nehrim mopy.  Maybe there is some way to copy one to 
the other without destroying the database of which files are installed.  
I'll have to experiment a bit.

**Comment by Utumno** [comment]
Some info on omods by AnyOldName in https://discord.com/channels/537706885965676554/537710082755133460/925054352895402096 and some remarks on BAIN handling by MO starting here: https://discord.com/channels/537706885965676554/537708965942001685/920742667422408754
