### ISSUE TITLE
Initial Starfield Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#667]
Central issue for tracking support. This is not about adding Bashed Patch support yet, just the basics for now (like FO4 before #482).

# Needed Info
- [x] What files are in the Data folder by default? - https://github.com/wrye-bash/wrye-bash/issues/667#issuecomment-1703920579
  - [ ] There is a second Data folder in `My Games\Starfield\Data` that takes priority over the game's Data folder
    - [ ] Vortex replaces that one with a junction linking back to the main Data folder, we may have to take that account when we add support for the second folder
- [ ] Where is the load order stored?
  - [x] Speaking of LO, which of the plugins in the Data folder are forcibly active? - https://github.com/wrye-bash/wrye-bash/issues/667#issuecomment-1704061884
  - [x] Is there anything in `Starfield.ccc`? - no `Starfield.ccc` yet, though the game does look for it.
  - [ ] It seems the LO is in `plugins.txt`, but it's bugged - the game doesn't create it but does read it, but it also can't even load third-party plugins right now.
  - [ ] There appears to be a new flag (`0x200`, what the ESL flag used to be) that makes plugins not take up a load order slot, but prevents them from adding new records. Would be really great for unlimited conflict resolution patches! But let's wait until we have confirmation how that works.
- [x] Has the BA2 structure changed?
  - [x] Apparently compression changed? - Yes and no. v2 BA2s are unchanged (except for two new unknowns in the header), but v3 BA2s have a third unknown in the header and use LZ4 *block* compression - note SSE uses LZ4 *frame* compression.
  - [x] Extension is still `.ba2` & `GNRL` vs `DX10` is still a thing, according to xEdit sources.
  - [x] Valid BA2 versions seem to be `2` and `3` - general BA2s use version 2, texture BA2s use version 3
  - [x] Starfield seems to use forward slashes in its BA2s by default, important once we want to write them (we already handle reading forward slashes correctly since many modded BSAs used them in previous games).
- [x] We need the icon, extracted from the official EXE. - https://github.com/wrye-bash/wrye-bash/issues/667#issuecomment-1703927217
- [x] SF does not seem to have registry keys? If so, we need to accelerate our plans for a new Steam detection method (see https://github.com/wrye-bash/wrye-bash/issues/667#issuecomment-1704063808).
- [x] Does SF support ESLs? What about `.esl` files? - yes, but the flag is `0x100`, not `0x200`
- [x] Are the plugin-name-specific dirs the same (i.e. do `sound/voice`, `meshes/actors/character/facegendata/facegeom` and `meshes/actors/character/facecustomization` have folders with plugin names in them)? Are there new ones? - there are three: `meshes/actors/character/facegendata/facegeom`, `sound/voice` and `textures/actors/character/facecustomization/starfield.esm`.
- [ ] What about INIs?
  - [ ] What's the name of the 'default' INI in the game folder? `Starfield.ini`?
  - [ ] What's the default game language? `en`?
  - [x] What INIs are present in the `My Games` folder? Is there even a `My Games` folder? - Yes, it has only `StarfieldPrefs.ini` though.
  - [x] Does SF have the same BA2-loading keys as FO4? I.e. `sResourceIndexFileList`, `sResourceStartUpArchiveList`, `sResourceArchiveList`, `sResourceArchiveList2` and `sResourceArchiveListBeta`? - latter two don't exist anymore, see https://stepmodifications.org/forum/topic/19019-starfield-default-values-for-all-known-valid-ini-settings/
- [x] I assume SF uses Papyrus. Is the extension the same (`.psc`/`.pex`)? What about the folder it's in (`scripts`)?
- [x] What about saves?
  - [x] The extension is `.sfs`, seen on many Nexus save uploads.
  - [x] What does the header look like? - The whole thing is wrapped inside a new `BCPS` zlib-compressed container, save screenshots don't seem to exist anymore, but beyond that the header is similar. There are two unknown bytes after the master list that clearly belong to it (master list size stored in the save is e.g. 82, but we only get 80 bytes by reading regular + ESL masters) - maybe a new override-only plugin block?
- [ ] What about record structure?
  - [x] Is it generally the same in terms of records, headers and subrecords? - Yes, though Bethesda has made the plugin format *much* worse yet again (`REFL` and `BFCB`/`BFCE`).
  - [x] Does SF have the expanded plugin range from FO4 (i.e. start from `0x001` instead of `0x800`)? Does Next Object ID begin at `0x001`? - Yes, it appears so.
  - [x] Does the file extension force ESM/ESL flags like in FO4 and SSE? - Yes, confirmed by aers on Discord.
  - [x] Only valid header version appears to be `0.96`, according to xEdit sources.
  - [ ] Is the maximum leveled list size still 255? Are there even leveled lists?
  - [ ] Has someone dumped the CTDA functions yet? - Nope.
    - [ ] Is there a `GetVATSValue` function with the same quirk as in earlier games?
  - [x] What are the top GRUPs? - https://github.com/TES5Edit/TES5Edit/blob/c3f0246f3836888732273611e16754ba7c2e0c65/Core/wbDefinitionsSF1.pas#L17445-L17619
  - [ ] Which GRUPs are complex, i.e. have a non-flat structure?
  - [x] I implemented a basic `TES4` record, does it work? - Yes.
    - [ ] There seems to be one new subrecord in it (`CHGL`) that hasn't been decoded yet.
- [ ] The game tries to read plugins etc. from both the Data folder and from My Documents. Do we have to implement reading from there? Because that will be nigh-on impossible.
- [ ] What about localized plugins?
  - [ ] Does SF still use strings files?
  - [ ] If yes, has the strings format changed? And are they still in the same folder with the same naming convention?
- [x] Add a proper SFSE link, currently just links to the github.

# Later Stuff
- [ ] Add CK info once the CK comes out.
- [ ] Does SF have achlists? Probably need to wait for the CK?
- [ ] Check what key `SF1Edit` uses (guessing `sf1View`).
- [ ] Any useful INI tweaks?
  - [x] The enable/disable loose files tweak is needed again.
- [ ] Wait for the CK, then see if they made the same mistake with `source/scripts` again.

# Links
- LOOT issue: https://github.com/loot/loot/issues/1882
- Current xEdit definitions: https://github.com/TES5Edit/TES5Edit/commits/dev-4.1.5/Core/wbDefinitionsSF1.pas
- Documentation on the horrible CDB format used for `REFL` data and terrain: https://github.com/gibbed/Gibbed.Starfield/tree/main/projects/Gibbed.Starfield.FileFormats

**Comment by Infernio** [comment]
Initial branch is up at `inf-667-starfield`. Search for `TODO(SF)` to find all open questions.

**Comment by Arthmoor** [comment]
The INI file the game made: Documents\My Games\Starfield\StarfieldPrefs.ini

Location of load order is unknown - no plugins.txt file exists in AppData\Local

**Comment by Arthmoor** [comment]
Starfield - Voices01.ba2
Starfield - Voices02.ba2
Starfield - VoicesPatch.ba2
Starfield - WwiseSounds01.ba2
Starfield - WwiseSounds02.ba2
Starfield - WwiseSounds03.ba2
Starfield - WwiseSounds04.ba2
Starfield - WwiseSounds05.ba2
Starfield - WwiseSoundsPatch.ba2
Starfield.esm
BlueprintShips-Starfield - Localization.ba2
BlueprintShips-Starfield.esm
Constellation - Localization.ba2
Constellation - Textures.ba2
Constellation.esm
data.bin
OldMars - Localization.ba2
OldMars - Textures.ba2
OldMars.esm
Starfield - Animations.ba2
Starfield - DensityMaps.ba2
Starfield - FaceAnimation01.ba2
Starfield - FaceAnimation02.ba2
Starfield - FaceAnimation03.ba2
Starfield - FaceAnimation04.ba2
Starfield - FaceAnimationPatch.ba2
Starfield - FaceMeshes.ba2
Starfield - GeneratedTextures.ba2
Starfield - Interface.ba2
Starfield - Localization.ba2
Starfield - LODMeshes.ba2
Starfield - LODMeshesPatch.ba2
Starfield - LODTextures.ba2
Starfield - Materials.ba2
Starfield - Meshes01.ba2
Starfield - Meshes02.ba2
Starfield - MeshesPatch.ba2
Starfield - Misc.ba2
Starfield - Particles.ba2
Starfield - ParticlesTestData.ba2
Starfield - PlanetData.ba2
Starfield - Shaders.ba2
Starfield - ShadersBeta.ba2
Starfield - Terrain01.ba2
Starfield - Terrain02.ba2
Starfield - Terrain03.ba2
Starfield - Terrain04.ba2
Starfield - TerrainPatch.ba2
Starfield - Textures01.ba2
Starfield - Textures02.ba2
Starfield - Textures03.ba2
Starfield - Textures04.ba2
Starfield - Textures05.ba2
Starfield - Textures06.ba2
Starfield - Textures07.ba2
Starfield - Textures08.ba2
Starfield - Textures09.ba2
Starfield - Textures10.ba2
Starfield - Textures11.ba2
Starfield - TexturesPatch.ba2

"video" Folder (yes, it's an all lowecase folder name) in Data which contains:

PowerVision_VoidForm.bk2
ArtifactVision01.bk2
ArtifactVision02.bk2
ArtifactVision03.bk2
ArtifactVision04.bk2
ArtifactVision05.bk2
ArtifactVision06.bk2
ArtifactVision07.bk2
ArtifactVision08.bk2
ArtifactVision09.bk2
BGS_LOGO_1080p_BinkVersion.bk2
EndingVision.bk2
MainMenuLoop.bk2
PowerVision_Alien.bk2
PowerVision_AntiGravField.bk2
PowerVision_CreateVac.bk2
PowerVision_CreatorsPeace.bk2
PowerVision_Earthbound.bk2
PowerVision_Elemental.bk2
PowerVision_Eternal.bk2
PowerVision_GravDash.bk2
PowerVision_GravityWave.bk2
PowerVision_GravityWell.bk2
PowerVision_InnerDemon.bk2
PowerVision_LifeForced.bk2
PowerVision_MoonForm.bk2
PowerVision_ParallelSelf.bk2
PowerVision_ParticleBeam.bk2
PowerVision_PersonalAtmosphere.bk2
PowerVision_PhasedTime.bk2
PowerVision_Precognition.bk2
PowerVision_ReactiveShield.bk2
PowerVision_SenseStar.bk2
PowerVision_SolarFlare.bk2
PowerVision_SunlessSpace.bk2
PowerVision_Supernova.bk2

**Comment by Arthmoor** [comment]
There is no Starfield.ccc file right now. Unsure of whether one will exist in future or not since Bethesda has not commented on any Creation Club support yet.

Forced loads for everyone:

Starfield.esm
BlueprintShips-Starfield.esm

If present these are also being forced to load:

Constellation.esm
OldMars.esm

Those last 2 .esm files are preorder and premium copy bonuses so not everyone is going to have them.

**Comment by Arthmoor** [comment]
Starfield - Misc.ba2 contains all of the scripts, which would unpack into the usual Data\Scripts folder. They're definitely still Papyrus.

No source code is available yet, that won't drop until the CK does.

**Comment by Arthmoor** [comment]
Extracted the Starfield.ico file - wasn't sure what size you wanted so I grabbed the biggest one that IconViewer would let me.

[StarfieldIcon.zip](https://github.com/wrye-bash/wrye-bash/files/12504640/StarfieldIcon.zip)

**Comment by Arthmoor** [comment]
And the last bit of comment spam for now - the only registry entry actually relevant to the game I could find was in:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 1716740

Not sure what else you'd need from that, but it's the Steam information I assume you were talking about.

**Comment by Infernio** [comment]
Thanks 👍

**Comment by Infernio** [comment]
Is the right fixed order
```
Starfield.esm
BlueprintShips-Starfield.esm
Constellation.esm
OldMars.esm
```
?

**Comment by Ortham** [comment]
> There is no Starfield.ccc file right now. Unsure of whether one will exist in future or not since Bethesda has not commented on any Creation Club support yet.

The game does look for one.

> * Valid BA2 versions seem to be `2` and `3`, according to xEdit sources.

Where did whoever wrote this see version 3? I've only spotted 2 so far.

Cross-linking with loot/loot#1882 as I've already got answers to some of the OP's questions written there.

**Comment by Ortham** [comment]
> Is the right fixed order
> 
> ```
> Starfield.esm
> BlueprintShips-Starfield.esm
> Constellation.esm
> OldMars.esm
> ```
> 
> ?

Nope, it's

Starfield.esm
Constellation.esm
OldMars.esm
BlueprintShips-Starfield.esm

(I just figured that out in the last hour)

**Comment by Ortham** [comment]
Also regarding game detection / Linux support, LOOT's got that now implemented using Steam's libraryfolders.vdf and appmanifest files - it was pretty straightforward, except that the app IDs listed in the libraryfolders.vdf is not necessarily up to date (installing doesn't always add it, uninstalling doesn't always remove it), so LOOT instead speculatively tries to open the app manifest files for all supported games in all configured library folders, otherwise you have to tell people to relaunch Steam before you'll see the games (adding or removing library folders also does the job).

**Comment by Infernio** [comment]
xEdit has this:
https://github.com/TES5Edit/TES5Edit/blob/c3f0246f3836888732273611e16754ba7c2e0c65/Core/wbBSArchive.pas#L510-L511

I don't know where the info comes from.

> LOOT's got that now implemented using Steam's libraryfolders.vdf and appmanifest files

That is exactly what I'm planning too.

**Comment by Ortham** [comment]
> xEdit has this: https://github.com/TES5Edit/TES5Edit/blob/c3f0246f3836888732273611e16754ba7c2e0c65/Core/wbBSArchive.pas#L510-L511
> 
> I don't know where the info comes from.

Git blames @ElminsterAU, not sure if @'ing him will notify him but hopefully he'll be able to answer.

**Comment by ElminsterAU** [comment]
I just committed it. Code came from zilav, and initial information from the SkyrimSE RE discord. Works well enough they SF1View doesn't crash when loading the BSA. That's all I can say so far.

**Comment by Ortham** [comment]
I had a look myself and all the `Starfield - Textures*.ba2` files and `Starfield - LODTextures.ba2` have a version of 3, the others are all version 2.

**Comment by Arthmoor** [comment]
`Are the plugin-name-specific dirs the same (i.e. does meshes/actors/character/facegendata/facegeom and meshes/actors/character/facecustomization have folders with plugin names in them)? Are there new ones?`

Those 2 folders don't appear to exist. So no idea if or how they're handling facegen this time.

**Comment by Infernio** [comment]
Does `sound/voice/[plugin name]` still exist?

**Comment by Arthmoor** [comment]
Yes, those files are in the 2 voice BA2 archives.

**Comment by BeermotorWB** [comment]
>  Are the plugin-name-specific dirs the same (i.e. do sound/voice, meshes/actors/character/facegendata/facegeom and meshes/actors/character/facecustomization have folders with plugin names in them)? Are there new ones? - sound/voice is still a thing, unsure about others.

Face meshes appear to be in 
`meshes\actors\character\facegendata\facegeom\starfield.esm`

There are also face mesh files (.mesh extension) that are present. 

Voice and animation files are a different format (no more fuz) but are in the same general dir structure.
Same with Terrain and LOD. 

I'll confirm textures once the texture BA2 format is conquered. 

Interestingly, galaxy/star behaviors and biomes are stored as CSV data under `data\space\`

**Comment by Arthmoor** [comment]
> Face meshes appear to be in
> meshes\actors\character\facegendata\facegeom\starfield.esm

Which archive are those in? I didn't see them when I was looking.

**Comment by ElminsterAU** [comment]
> Interestingly, galaxy/star behaviors and biomes are stored as CSV data under `data\space\`

I'm quite sure these are not used. They are probably the data that at some point has been imported into Starfield.esm, but has been changed there since then.

**Comment by Infernio** [comment]
Force-pushed the branch. The latest commit on it implements the new Steam detection (and refactors a whole bunch), so Starfield should now get detected automatically without needing to pass `-o`, edit `bash.ini`, etc.
